title: Kevin Pacayra # your name (or website title) here
logo: "/images/DSC_0831 copy.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A career-shifter from the Philippines with passion to programming specifically to web development and data science.
  <br><br>
  I am currently learning Javascript and jQuery library. I worked on ICO cryptocurrency from the past as Community and Social Media Manager.
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-pacayra-24108415a/">LinkedIn</a>
